#!/bin/sh
set -e

read_json_string() {
  key="$1"
  sed -n "s/.*\"$key\": \"\([^\"]*\)\".*/\1/p" /app/config.json | sed -n '1p'
}

read_json_bool() {
  key="$1"
  sed -n "s/.*\"$key\": \(true\|false\).*/\1/p" /app/config.json | sed -n '1p'
}

read_first_homeserver() {
  sed -n '/"homeserverList"[[:space:]]*:/,/]/ { s/^[[:space:]]*"\([^"]*\)".*/\1/p; }' /app/config.json | sed -n '1p'
}

# ── config.json ──────────────────────────────────────────────────────────────
# Generate from template only when runtime config actually needs overriding.
# The default rollout values (voiceStateMode=livekit, feature flags=false) should
# NOT force regeneration, otherwise we'd overwrite the shipped config.json.
if [ -n "$MESH_HOMESERVER" ] || [ -n "$MESH_LIVEKIT_URL" ] || [ -n "$MESH_PRESENCE_URL" ] || [ "$MESH_VOICE_STATE_MODE" = "bridge" ] || [ "$MESH_AUTHORITATIVE_BRIDGE_MODE" = "true" ]; then
  echo "[entrypoint] Generating config.json from environment variables..."
  MESH_HOMESERVER="${MESH_HOMESERVER:-$(read_first_homeserver)}"
  MESH_LIVEKIT_URL="${MESH_LIVEKIT_URL:-$(read_json_string livekitServiceUrl)}"
  MESH_PRESENCE_URL="${MESH_PRESENCE_URL:-$(read_json_string presenceUrl)}"
  MESH_VOICE_STATE_MODE="${MESH_VOICE_STATE_MODE:-$(read_json_string voiceStateMode)}"
  MESH_AUTHORITATIVE_BRIDGE_MODE="${MESH_AUTHORITATIVE_BRIDGE_MODE:-$(read_json_bool authoritativeBridgeMode)}"
  MESH_ALLOW_CUSTOM_HOMESERVERS="${MESH_ALLOW_CUSTOM_HOMESERVERS:-$(read_json_bool allowCustomHomeservers)}"

  : "${MESH_HOMESERVER:=matrix.org}"
  : "${MESH_PRESENCE_URL:=/api/presence}"
  : "${MESH_VOICE_STATE_MODE:=livekit}"
  : "${MESH_AUTHORITATIVE_BRIDGE_MODE:=false}"
  : "${MESH_ALLOW_CUSTOM_HOMESERVERS:=true}"
  : "${BRIDGE_AUTH_SECRET:=}"
  : "${MESH_TOKEN_STORAGE_MODE:=encrypted-local}"

  export MESH_HOMESERVER MESH_LIVEKIT_URL MESH_PRESENCE_URL \
    MESH_VOICE_STATE_MODE MESH_AUTHORITATIVE_BRIDGE_MODE \
    MESH_ALLOW_CUSTOM_HOMESERVERS BRIDGE_AUTH_SECRET MESH_TOKEN_STORAGE_MODE

  envsubst < /app/config.template.json > /app/config.json
  echo "[entrypoint] Done. config.json:"
  cat /app/config.json
fi

# ── config-microapps.js ───────────────────────────────────────────────────────
# Always regenerate so the browser gets fresh URLs on every container start.
# MESH_POLLS_URL      — public URL of the nordeck/matrix-poll-widget container
#                             e.g. https://polls.your-domain.com
# MESH_WHITEBOARD_URL — public URL of the nordeck/matrix-neoboard-widget container
#                             e.g. https://whiteboard.your-domain.com
# Leave a variable unset (or empty) to hide that app from the Activities catalog.
echo "[entrypoint] Generating config-microapps.js..."
cat > /app/config-microapps.js << JSEOF
/* Generated by docker-entrypoint.sh — do not edit */
window.__MESH_MICROAPPS__ = {
  pollsWidgetUrl: "${MESH_POLLS_URL:-}",
  whiteboardWidgetUrl: "${MESH_WHITEBOARD_URL:-}"
};
JSEOF
echo "[entrypoint] config-microapps.js:"
cat /app/config-microapps.js

exec nginx -g 'daemon off;'
