server {
  listen 80;
  listen [::]:80;

  location = /config.json {
    root /usr/share/nginx/html;
    add_header Cache-Control "no-store, no-cache, must-revalidate";
    add_header Pragma "no-cache";
  }

  location / {
    root /usr/share/nginx/html;

    rewrite ^/manifest.json$ /manifest.json break;

    rewrite ^/sw.js$ /sw.js break;
    rewrite ^/pdf.worker.min.js$ /pdf.worker.min.js break;

    rewrite ^/public/(.*)$ /public/$1 break;
    rewrite ^/assets/(.*)$ /assets/$1 break;

    rewrite ^(.+)$ /index.html break;
  }
}
