#!/bin/sh
set -e

# ── config.json ──────────────────────────────────────────────────────────────
# Generate from template if any homeserver / LiveKit vars are set.
# Otherwise the shipped config.json (with defaults) is used as-is.
if [ -n "$BETTERCORD_HOMESERVER" ] || [ -n "$BETTERCORD_LIVEKIT_URL" ] || [ -n "$BETTERCORD_PRESENCE_URL" ]; then
  echo "[entrypoint] Generating config.json from environment variables..."
  BETTERCORD_HOMESERVER="${BETTERCORD_HOMESERVER:-matrix.org}" \
  BETTERCORD_LIVEKIT_URL="${BETTERCORD_LIVEKIT_URL:-}" \
  BETTERCORD_PRESENCE_URL="${BETTERCORD_PRESENCE_URL:-}" \
  envsubst < /app/config.template.json > /app/config.json
  echo "[entrypoint] Done. config.json:"
  cat /app/config.json
fi

# ── config-microapps.js ───────────────────────────────────────────────────────
# Always regenerate so the browser gets fresh URLs on every container start.
# BETTERCORD_POLLS_URL      — public URL of the nordeck/matrix-poll-widget container
#                             e.g. https://polls.your-domain.com
# BETTERCORD_WHITEBOARD_URL — public URL of the nordeck/matrix-neoboard-widget container
#                             e.g. https://whiteboard.your-domain.com
# Leave a variable unset (or empty) to hide that app from the Activities catalog.
echo "[entrypoint] Generating config-microapps.js..."
cat > /app/config-microapps.js << JSEOF
/* Generated by docker-entrypoint.sh — do not edit */
window.__BC_MICROAPPS__ = {
  pollsWidgetUrl: "${BETTERCORD_POLLS_URL:-}",
  whiteboardWidgetUrl: "${BETTERCORD_WHITEBOARD_URL:-}"
};
JSEOF
echo "[entrypoint] config-microapps.js:"
cat /app/config-microapps.js

exec nginx -g 'daemon off;'
