#!/bin/sh
set -e

read_json_string() {
  key="$1"
  sed -n "s/.*\"$key\": \"\([^\"]*\)\".*/\1/p" /app/config.json | sed -n '1p'
}

read_json_bool() {
  key="$1"
  sed -n "s/.*\"$key\": \(true\|false\).*/\1/p" /app/config.json | sed -n '1p'
}

read_first_homeserver() {
  sed -n '/"homeserverList"[[:space:]]*:/,/]/ { s/^[[:space:]]*"\([^"]*\)".*/\1/p; }' /app/config.json | sed -n '1p'
}

# ── config.json ──────────────────────────────────────────────────────────────
# Generate from template only when runtime config actually needs overriding.
# The default rollout values (voiceStateMode=livekit, feature flags=false) should
# NOT force regeneration, otherwise we'd overwrite the shipped config.json.
if [ -n "$BETTERCORD_HOMESERVER" ] || [ -n "$BETTERCORD_LIVEKIT_URL" ] || [ -n "$BETTERCORD_PRESENCE_URL" ] || [ "$BETTERCORD_VOICE_STATE_MODE" = "bridge" ] || [ "$BETTERCORD_AUTHORITATIVE_BRIDGE_MODE" = "true" ] || [ "$BETTERCORD_DISABLE_MATRIX_PRESENCE_WRITES" = "true" ]; then
  echo "[entrypoint] Generating config.json from environment variables..."
  BETTERCORD_HOMESERVER="${BETTERCORD_HOMESERVER:-$(read_first_homeserver)}"
  BETTERCORD_LIVEKIT_URL="${BETTERCORD_LIVEKIT_URL:-$(read_json_string livekitServiceUrl)}"
  BETTERCORD_PRESENCE_URL="${BETTERCORD_PRESENCE_URL:-$(read_json_string presenceUrl)}"
  BETTERCORD_VOICE_STATE_MODE="${BETTERCORD_VOICE_STATE_MODE:-$(read_json_string voiceStateMode)}"
  BETTERCORD_AUTHORITATIVE_BRIDGE_MODE="${BETTERCORD_AUTHORITATIVE_BRIDGE_MODE:-$(read_json_bool authoritativeBridgeMode)}"
  BETTERCORD_DISABLE_MATRIX_PRESENCE_WRITES="${BETTERCORD_DISABLE_MATRIX_PRESENCE_WRITES:-$(read_json_bool disableMatrixPresenceWrites)}"

  : "${BETTERCORD_HOMESERVER:=matrix.org}"
  : "${BETTERCORD_PRESENCE_URL:=/api/presence}"
  : "${BETTERCORD_VOICE_STATE_MODE:=livekit}"
  : "${BETTERCORD_AUTHORITATIVE_BRIDGE_MODE:=false}"
  : "${BETTERCORD_DISABLE_MATRIX_PRESENCE_WRITES:=false}"

  export BETTERCORD_HOMESERVER BETTERCORD_LIVEKIT_URL BETTERCORD_PRESENCE_URL \
    BETTERCORD_VOICE_STATE_MODE BETTERCORD_AUTHORITATIVE_BRIDGE_MODE \
    BETTERCORD_DISABLE_MATRIX_PRESENCE_WRITES

  envsubst < /app/config.template.json > /app/config.json
  echo "[entrypoint] Done. config.json:"
  cat /app/config.json
fi

# ── config-microapps.js ───────────────────────────────────────────────────────
# Always regenerate so the browser gets fresh URLs on every container start.
# BETTERCORD_POLLS_URL      — public URL of the nordeck/matrix-poll-widget container
#                             e.g. https://polls.your-domain.com
# BETTERCORD_WHITEBOARD_URL — public URL of the nordeck/matrix-neoboard-widget container
#                             e.g. https://whiteboard.your-domain.com
# Leave a variable unset (or empty) to hide that app from the Activities catalog.
echo "[entrypoint] Generating config-microapps.js..."
cat > /app/config-microapps.js << JSEOF
/* Generated by docker-entrypoint.sh — do not edit */
window.__BC_MICROAPPS__ = {
  pollsWidgetUrl: "${BETTERCORD_POLLS_URL:-}",
  whiteboardWidgetUrl: "${BETTERCORD_WHITEBOARD_URL:-}"
};
JSEOF
echo "[entrypoint] config-microapps.js:"
cat /app/config-microapps.js

exec nginx -g 'daemon off;'
